BART:
  model_1:
    HIDDEN_SIZE: 768
    TRAIN_BATCH_SIZE: 16
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 100
    LEARNING_RATE: 5.0e-05
    WEIGHT_DECAY: 0.01
    MAX_LEN: 128
    ENCODER_LAYERS: 12
    DECODER_LAYERS: 12
    NUM_ENCODER_ATTENTION_HEADS: 12
    NUM_DECODER_ATTENTION_HEADS: 12
    ENCODER_FFN_DIM: 3072
    DECODER_FFN_DIM: 3072
    VOCAB_SIZE: 30000
    MAX_POSITION_EMBEDDINGS: 514
    NUM_ATTENTION_HEADS: 12
    NUM_HIDDEN_LAYERS: 8
    TYPE_VOCAB_SIZE: 1
    optimizer: adam
    criterion: crossentropy
    early_stopping_toggle: true
    early_stopping_threshold: 5.0e-05
    early_stopping_patience: 5
    lr_sched: null
  model_2:
    HIDDEN_SIZE: 768
    TRAIN_BATCH_SIZE: 16
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 100
    LEARNING_RATE: 5.0e-05
    WEIGHT_DECAY: 0.01
    MAX_LEN: 128
    ENCODER_LAYERS: 12
    DECODER_LAYERS: 12
    NUM_ENCODER_ATTENTION_HEADS: 12
    NUM_DECODER_ATTENTION_HEADS: 12
    ENCODER_FFN_DIM: 3072
    DECODER_FFN_DIM: 3072
    VOCAB_SIZE: 30000
    MAX_POSITION_EMBEDDINGS: 514
    NUM_ATTENTION_HEADS: 12
    NUM_HIDDEN_LAYERS: 8
    TYPE_VOCAB_SIZE: 1
    optimizer: adam
    criterion: crossentropy
    early_stopping_toggle: true
    early_stopping_threshold: 5.0e-05
    early_stopping_patience: 5
    lr_sched: null
  model_3:
    HIDDEN_SIZE: 768
    TRAIN_BATCH_SIZE: 16
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 100
    LEARNING_RATE: 5.0e-05
    WEIGHT_DECAY: 0.01
    MAX_LEN: 128
    ENCODER_LAYERS: 12
    DECODER_LAYERS: 12
    NUM_ENCODER_ATTENTION_HEADS: 12
    NUM_DECODER_ATTENTION_HEADS: 12
    ENCODER_FFN_DIM: 3072
    DECODER_FFN_DIM: 3072
    VOCAB_SIZE: 30000
    MAX_POSITION_EMBEDDINGS: 514
    NUM_ATTENTION_HEADS: 12
    NUM_HIDDEN_LAYERS: 8
    TYPE_VOCAB_SIZE: 1
    optimizer: adam
    criterion: crossentropy
    early_stopping_toggle: true
    early_stopping_threshold: 5.0e-05
    early_stopping_patience: 5
    lr_sched: null
  model_lipinski:
    HIDDEN_SIZE: 768
    TRAIN_BATCH_SIZE: 16
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 100
    LEARNING_RATE: 5.0e-05
    WEIGHT_DECAY: 0.01
    MAX_LEN: 128
    ENCODER_LAYERS: 12
    DECODER_LAYERS: 12
    NUM_ENCODER_ATTENTION_HEADS: 12
    NUM_DECODER_ATTENTION_HEADS: 12
    ENCODER_FFN_DIM: 3072
    DECODER_FFN_DIM: 3072
    VOCAB_SIZE: 30000
    MAX_POSITION_EMBEDDINGS: 514
    NUM_ATTENTION_HEADS: 12
    NUM_HIDDEN_LAYERS: 8
    TYPE_VOCAB_SIZE: 1
    optimizer: adam
    criterion: crossentropy
    early_stopping_toggle: true
    early_stopping_threshold: 5.0e-05
    early_stopping_patience: 5
    lr_sched: null
  model_nada:
    HIDDEN_SIZE: 768
    TRAIN_BATCH_SIZE: 16
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 100
    LEARNING_RATE: 5.0e-05
    WEIGHT_DECAY: 0.01
    MAX_LEN: 128
    ENCODER_LAYERS: 12
    DECODER_LAYERS: 12
    NUM_ENCODER_ATTENTION_HEADS: 12
    NUM_DECODER_ATTENTION_HEADS: 12
    ENCODER_FFN_DIM: 3072
    DECODER_FFN_DIM: 3072
    VOCAB_SIZE: 30000
    MAX_POSITION_EMBEDDINGS: 514
    NUM_ATTENTION_HEADS: 12
    NUM_HIDDEN_LAYERS: 8
    TYPE_VOCAB_SIZE: 1
    optimizer: adam
    criterion: crossentropy
    early_stopping_toggle: true
    early_stopping_threshold: 5.0e-05
    early_stopping_patience: 5
    lr_sched: null
